http:
  routers:
    homeassistant-rtr:
      entryPoints:
        - https
      middlewares:
        - chain-oauth@file
      service: homeassistant-svc
      rule: 'Host(`homeassistant.{{env "DOMAINNAME"}}`)'
      tls:
        certresolver: dns-cloudflare

    homeassistant-bypass-rtr:
      entryPoints:
        - https
      middlewares:
        - chain-no-auth@file
      service: homeassistant-svc
      rule: 'Host(`homeassistant.{{env "DOMAINNAME"}}`) && HeadersRegexp(`User-Agent`, `Home Assistant.*io.robbie.HomeAssistant.*`)'
      priority: 100
      tls:
        certresolver: dns-cloudflare

  services:
    homeassistant-svc:
      loadBalancer:
        servers:
          - url: 'http://{{env "SERVER_IP"}}:8123'
