http:
  middlewares:
    flatline-add-system:
      addPrefix:
        prefix: "/system"

  routers:
    flatline-rtr:
      entryPoints:
        - https
      middlewares:
        - chain-oauth@file
        # - flatline-add-system
      service: flatline-svc
      rule: 'Host(`flatline.{{env "DOMAINNAME"}}`)'
      tls:
        certresolver: dns-cloudflare

  services:
    flatline-svc:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: 'http://{{env "FLATLINE_IP"}}:{{env "COCKPIT_PORT"}}'
