http:
  routers:
    hdhomerun-rtr:
      entryPoints:
        - https
      middlewares:
        - chain-oauth@file
      service: hdhomerun-svc
      rule: 'Host(`hdhomerun.{{env "DOMAINNAME"}}`)'
      tls:
        certresolver: dns-cloudflare

  services:
    hdhomerun-svc:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: 'http://{{env "HDHOMERUN_IP"}}'
