http:
  routers:
    printer-rtr:
      entryPoints:
        - https
      middlewares:
        - chain-oauth@file
      service: printer-svc
      rule: 'Host(`printer.{{env "DOMAINNAME"}}`)'
      tls:
        certresolver: dns-cloudflare

  services:
    printer-svc:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: 'http://{{env "PRINTER_IP"}}'
