http:
  middlewares:
    add-protect:
      addPrefix:
        prefix: "/protect"

  routers:
    unifi-protect-rtr:
      entryPoints:
        - https
      middlewares:
        - chain-oauth@file
        - add-protect
      service: unifi-protect-svc
      rule: 'Host(`protect.{{env "DOMAINNAME"}}`)'
      tls:
        certresolver: dns-cloudflare

  services:
    unifi-protect-svc:
      loadBalancer:
        servers:
          - url: 'https://{{env "CLOUDKEY_IP"}}'
