http:
  middlewares:
    unifi-redirect:
      redirectRegex:
        regex: '^https?:\/\/([^.]+)\.([^/]+)\/?$'
        replacement: 'https://unifi.${2}/${1}'
        permanent: true

  routers:
    unifi-protect-rtr:
      entryPoints:
        - https
      middlewares:
        - chain-oauth@file
        - unifi-redirect
      service: unifi-cloudkey-svc
      rule: 'Host(`protect.{{env "DOMAINNAME"}}`)'
      tls:
        certresolver: dns-cloudflare

    unifi-network-rtr:
      entryPoints:
        - https
      middlewares:
        - chain-oauth@file
        - unifi-redirect
      service: unifi-cloudkey-svc
      rule: 'Host(`network.{{env "DOMAINNAME"}}`)'
      tls:
        certresolver: dns-cloudflare

    unifi-rtr:
      entryPoints:
        - https
      middlewares:
        - chain-oauth@file
      service: unifi-cloudkey-svc
      rule: 'Host(`unifi.{{env "DOMAINNAME"}}`)'
      tls:
        certresolver: dns-cloudflare

  services:
    unifi-cloudkey-svc:
      loadBalancer:
        servers:
          - url: 'https://{{env "CKG2_IP"}}'
