http:
  routers:
    homebridge-rtr:
      entryPoints:
        - https
      middlewares:
        - chain-oauth@file
      service: homebridge-svc
      rule: 'Host(`homebridge.{{env "DOMAINNAME"}}`)'
      tls:
        certresolver: dns-cloudflare

  services:
    homebridge-svc:
      loadBalancer:
        servers:
          - url: 'http://{{env "SERVER_IP"}}:8282'
