- platform: ping
  name: 'Nintendo Switch'
  host: !secret ip_nintendo_switch
  scan_interval: 120

# Create humidistat sensors (https://github.com/basschipper/homeassistant-generic-hygrostat)
- platform: generic_hygrostat
  name: Master Bathroom Hygrostat
  sensor: sensor.master_bathroom_weather_humidity
  max_on_time: 2700 # Optional safety max on time in seconds. Default = 7200 seconds

- platform: generic_hygrostat
  name: Guest Bathroom Hygrostat
  sensor: sensor.guest_bathroom_weather_humidity
  max_on_time: 2700
  delta_trigger: 6

- platform: generic_hygrostat
  name: Kids Bathroom Hygrostat
  sensor: sensor.kids_bathroom_weather_humidity
  max_on_time: 2700

# Consolidate motion sensors for rooms that have multiple sensors
- platform: template
  sensors:
    garage_motion_any:
      friendly_name: "Garage Motion (any)"
      device_class: motion
      unique_id: binary_sensor.garage_motion_any
      value_template: >-
        {{ is_state('binary_sensor.garage_motion_ias_zone', 'on')
           or is_state('binary_sensor.motion_garage_protect', 'on') }}
    living_room_motion_any:
      friendly_name: "Living Room Motion (any)"
      device_class: motion
      unique_id: binary_sensor.living_room_motion_any
      value_template: >-
        {{ is_state('binary_sensor.living_room_motion_ias_zone', 'on')
           or is_state('binary_sensor.motion_living_room_protect', 'on') }}
    sunroom_motion_any:
      friendly_name: "Sunroom Motion (any)"
      device_class: motion
      unique_id: binary_sensor.sunroom_motion_any
      value_template: >-
        {{ is_state('binary_sensor.motion_sunroom_protect', 'on')
           or is_state('binary_sensor.sunroom_motion_ias_zone', 'on') }}
    dining_room_motion_any:
      friendly_name: "Dining Room Motion (any)"
      device_class: motion
      unique_id: binary_sensor.dining_room_motion_any
      value_template: >-
        {{ is_state('binary_sensor.dining_room_motion_ias_zone', 'on')
           or is_state('binary_sensor.master_bedroom_motion_hue_occupancy', 'on')
           or is_state('binary_sensor.motion_dining_room_protect', 'on') }}
    guest_room_motion_any:
      friendly_name: "Guest Room Motion (any)"
      device_class: motion
      unique_id: binary_sensor.guest_room_motion_any
      value_template: >-
        {{ is_state('binary_sensor.guest_room_motion_ias_zone', 'on')
           or is_state('binary_sensor.motion_guest_room_protect', 'on') }}
    master_bedroom_motion_any:
      friendly_name: "Master Bedroom Motion (any)"
      device_class: motion
      unique_id: binary_sensor.master_bedroom_motion_any
      value_template: >-
        {{ is_state('binary_sensor.master_bedroom_motion_occupancy', 'on') }}
    downstairs_motion_any:
      friendly_name: "Downstairs Motion (any)"
      device_class: motion
      unique_id: binary_sensor.downstairs_motion_any
      value_template: >-
        {{ is_state('binary_sensor.mudroom_motion_ias_zone', 'on')
           or is_state('binary_sensor.kitchen_motion_any', 'on')
           or is_state('binary_sensor.living_room_motion_any', 'on')
           or is_state('binary_sensor.dining_room_motion_any', 'on')
           or is_state('binary_sensor.sunroom_motion_any', 'on') }}
    motion_front_door_protect_person:
      friendly_name: "Motion Front Door Protect Person"
      device_class: motion
      unique_id: binary_sensor.motion_front_door_protect_person
      value_template: >-
        {{ is_state('binary_sensor.motion_front_door_protect', 'on') and state_attr('binary_sensor.motion_front_door_protect', 'event_object').lower() == 'person' }}
