
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate
    base_url: https://homeassistant.jlaska.com

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  customize: !include customize.yaml

# Include themes directory
frontend:
  themes: !include_dir_merge_named themes

logger:
  default: warning
  logs: {}

http:
  use_x_forwarded_for: true
  trusted_proxies: !secret trusted_proxies

# LFX UDP broadcast isn't working on my network
lifx:
  light:
    - broadcast: !secret lifx_mini_ip
    - broadcast: !secret lifx_z_1_ip
    - broadcast: !secret lifx_z_2_ip

sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
light: !include lights.yaml
fan: !include fans.yaml
template: !include templates.yaml
# zwave: !include zwave.yaml
zha: !include zha.yaml
homekit: !include homekit.yaml

# Google Nest Integration
nest:
  client_id: !secret google_nest_client_id
  client_secret: !secret google_nest_client_secret
  project_id: !secret google_nest_project_id
  subscriber_id: !secret google_nest_subscriber_id

# Use camera plugin for forcast/doplar images
camera:
  - platform: generic
    still_image_url: !secret weather_doplar_url
    name: Weather Doplar Radar
  - platform: generic
    still_image_url: !secret weather_forecast_url
    name: Weather 7 Day Forecast
  - platform: generic
    name: US Atlantic Coast
    still_image_url: !secret weather_noaa_us_east_coast
  - platform: generic
    name: US Southeast
    still_image_url: !secret weather_noaa_us_southeast
  - platform: generic
    name: US Continent
    still_image_url: !secret weather_noaa_us

google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_client_secret
  calendar_access: read_only

downloader:
  download_dir: downloads
