
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate
    base_url: https://homeassistant.jlaska.com

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  customize: !include customize.yaml

# Include themes directory
frontend:
  themes: !include_dir_merge_named themes

logger:
  default: warn

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret reverse_proxy_ip

# LFX UDP broadcast isn't working on my network
lifx:
  light:
    - broadcast: !secret lifx_mini_ip
    - broadcast: !secret lifx_z_1_ip
    - broadcast: !secret lifx_z_2_ip

sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
light: !include lights.yaml
fan: !include fans.yaml

zwave: !include zwave.yaml
zha: !include zha.yaml

# Google Nest Integration
nest:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret
  project_id: !secret google_project_id
  subscriber_id: !secret google_subscriber_id

# Use camera plugin for forcast/doplar images
camera:
  - platform: generic
    still_image_url: !secret weather_doplar_url
    name: Weather Doplar Radar
  - platform: generic
    still_image_url: !secret weather_forecast_url
    name: Weather 7 Day Forecast

homekit:
  - filter:
      include_domains:
        - light
        - fan
      include_entity_globs:
        - switch.*_on_off
        - binary_sensor.*_ias_zone
      exclude_entities:
        - light.living_room_table_lamp
      exclude_entity_globs:
        - light.living_room_bookshelf*
