- platform: template
  fans:
    guest_bathroom_fan:
      friendly_name: "Guest Bathroom Fan"
      unique_id: "fan.guest_bathroom_fan"
      value_template: "{{ states('switch.guest_bathroom_fan_switch') }}"
      speed_count: 1
      turn_on:
        service: 'switch.turn_on'
        entity_id: 'switch.guest_bathroom_fan_switch'
      turn_off:
        service: 'switch.turn_off'
        entity_id: 'switch.guest_bathroom_fan_switch'
    guest_room_fan:
      friendly_name: "Guest Room Fan"
      unique_id: "fan.guest_room_fan"
      value_template: "{{ states('switch.guest_room_fan_switch') }}"
      speed_count: 1
      turn_on:
        service: 'switch.turn_on'
        entity_id: 'switch.guest_room_fan_switch'
      turn_off:
        service: 'switch.turn_off'
        entity_id: 'switch.guest_room_fan_switch'
    henrys_room_fan:
      friendly_name: "Henry's Room Fan"
      unique_id: "fan.henrys_room_fan"
      value_template: "{{ states('switch.henrys_room_fan_switch') }}"
      speed_count: 1
      turn_on:
        service: 'switch.turn_on'
        entity_id: 'switch.henrys_room_fan_switch'
      turn_off:
        service: 'switch.turn_off'
        entity_id: 'switch.henrys_room_fan_switch'
    living_room_fan:
      friendly_name: "Living Room Fan"
      unique_id: "fan.living_room_fan"
      value_template: "{{ states('switch.living_room_fan_switch') }}"
      speed_count: 1
      turn_on:
        service: 'switch.turn_on'
        entity_id: 'switch.living_room_fan_switch'
      turn_off:
        service: 'switch.turn_off'
        entity_id: 'switch.living_room_fan_switch'
    master_bathroom_fan:
      friendly_name: "Master Bathroom Fan"
      unique_id: "fan.master_bathroom_fan"
      value_template: "{{ states('switch.master_bathroom_fan_switch') }}"
      speed_count: 1
      turn_on:
        service: 'switch.turn_on'
        entity_id: 'switch.master_bathroom_fan_switch'
      turn_off:
        service: 'switch.turn_off'
        entity_id: 'switch.master_bathroom_fan_switch'
    master_bathroom_toilet_fan:
      friendly_name: "Master Bathroom Toilet Fan"
      unique_id: "fan.master_bathroom_toilet_fan"
      value_template: "{{ states('switch.master_bathroom_toilet_fan_switch') }}"
      speed_count: 1
      turn_on:
        service: 'switch.turn_on'
        entity_id: 'switch.master_bathroom_toilet_fan_switch'
      turn_off:
        service: 'switch.turn_off'
        entity_id: 'switch.master_bathroom_toilet_fan_switch'
    master_bedroom_fan:
      friendly_name: "Master Bedroom Fan"
      unique_id: "fan.master_bedroom_fan"
      value_template: "{{ states('switch.master_bedroom_fan_switch') }}"
      speed_count: 1
      turn_on:
        service: 'switch.turn_on'
        entity_id: 'switch.master_bedroom_fan_switch'
      turn_off:
        service: 'switch.turn_off'
        entity_id: 'switch.master_bedroom_fan_switch'
    sunroom_fan:
      friendly_name: "Sunroom Fan"
      unique_id: "fan.sunroom_fan"
      value_template: "{{ states('switch.sunroom_fan_switch') }}"
      speed_count: 1
      turn_on:
        service: 'switch.turn_on'
        entity_id: 'switch.sunroom_fan_switch'
      turn_off:
        service: 'switch.turn_off'
        entity_id: 'switch.sunroom_fan_switch'
    williams_room_fan:
      friendly_name: "William's Room Fan"
      unique_id: "fan.williams_room_fan"
      value_template: "{{ states('switch.williams_room_fan_switch') }}"
      speed_count: 1
      turn_on:
        service: 'switch.turn_on'
        entity_id: 'switch.williams_room_fan_switch'
      turn_off:
        service: 'switch.turn_off'
        entity_id: 'switch.williams_room_fan_switch'
    powder_room_fan:
      friendly_name: "Powder Room Fan"
      unique_id: "fan.powder_room_fan"
      value_template: "{{ states('switch.powder_room_fan_switch') }}"
      speed_count: 1
      turn_on:
        service: 'switch.turn_on'
        entity_id: 'switch.powder_room_fan_switch'
      turn_off:
        service: 'switch.turn_off'
        entity_id: 'switch.powder_room_fan_switch'
