- platform: template
  sensors:
    # Create several time/date sensors for use in dashboards
    time_hhmm:
      friendly_name: "Time (hh:mm)"
      icon_template: mdi:calendar-clock
      value_template: "{{ as_timestamp(states('sensor.date_time_iso')) | timestamp_custom('%-I:%M %p') }}"
    my_date:
      friendly_name: "Date (friendly)"
      icon_template: mdi:calendar
      value_template: "{{ as_timestamp(states('sensor.date_time_iso')) | timestamp_custom('%A, %B %d') }}"

    # Climacel Sensors, see also:
    #   - templates.yaml
    #   - https://community.home-assistant.io/t/ha-card-weather-conditions-setup-with-climacell-tomorrow-io-integration/314398)
    cc_grass_pollen_index_mod:
      friendly_name: Pollen Grass climacell
      icon_template: 'mdi:flower'
      value_template: >-
        {% if is_state('sensor.climacell_grass_pollen_index', 'none') %}
          0
        {% elif is_state('sensor.climacell_grass_pollen_index','very_low') %}
          1
        {% elif is_state('sensor.climacell_grass_pollen_index','low') %}
          2
        {% elif is_state('sensor.climacell_grass_pollen_index','medium') %}
          3
        {% elif is_state('sensor.climacell_grass_pollen_index','high') %}
          4
        {% elif is_state('sensor.climacell_grass_pollen_index','very_high') %}
          5
        {% else %}
          Unknown
        {% endif %}
    cc_tree_pollen_index_mod:
      friendly_name: Pollen Tree climacell
      icon_template: 'mdi:tree'
      value_template: >-
        {% if is_state('sensor.climacell_tree_pollen_index', 'none') %}
          0
        {% elif is_state('sensor.climacell_tree_pollen_index','very_low') %}
          1
        {% elif is_state('sensor.climacell_tree_pollen_index','low') %}
          2
        {% elif is_state('sensor.climacell_tree_pollen_index','medium') %}
          3
        {% elif is_state('sensor.climacell_tree_pollen_index','high') %}
          4
        {% elif is_state('sensor.climacell_tree_pollen_index','very_high') %}
          5
        {% else %}
          Unknown
        {% endif %}
    cc_weed_pollen_index_mod:
      friendly_name: Pollen Weed climacell
      icon_template: 'mdi:sprout'
      value_template: >-
        {% if is_state('sensor.climacell_weed_pollen_index', 'none') %}
          0
        {% elif is_state('sensor.climacell_weed_pollen_index','very_low') %}
          1
        {% elif is_state('sensor.climacell_weed_pollen_index','low') %}
          2
        {% elif is_state('sensor.climacell_weed_pollen_index','medium') %}
          3
        {% elif is_state('sensor.climacell_weed_pollen_index','high') %}
          4
        {% elif is_state('sensor.climacell_weed_pollen_index','very_high') %}
          5
        {% else %}
          Unknown
        {% endif %}

    dining_room_motion_hue_temperature_adjusted:
      friendly_name: "Dining Romo Motion Hue Temperature (adjusted)"
      icon_template: hass:thermometer
      value_template: "{{ states('sensor.dining_room_motion_hue_temperature')|float + 3.0 }}"

# Create time sensors
- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'date_time_iso'
    - 'time_date'

# Add moon phase sensor
- platform: moon
